### ISSUE TITLE
New brick texture

### ISSUE THREAD

**Issue by illyaveksler** [Evanyl/evanyl.github.io#1]
![brick](https://user-images.githubusercontent.com/68177204/87239477-77d9f300-c3c4-11ea-81bb-2358fee941ef.png)

**Comment by illyaveksler** [comment]
![brick_0 2](https://user-images.githubusercontent.com/68177204/87239503-c7b8ba00-c3c4-11ea-83e8-fb8a205a9f9b.png)

**Comment by illyaveksler** [comment]
![brick_0 3](https://user-images.githubusercontent.com/68177204/87239524-ed45c380-c3c4-11ea-9da2-6db2bcb58fcb.png)

**Comment by Evanyl** [comment]
Thank you ilyve
