### ISSUE TITLE
New ball texture

### ISSUE THREAD

**Issue by illyaveksler** [Evanyl/evanyl.github.io#3]
![ball](https://user-images.githubusercontent.com/68177204/87239950-a1e1e400-c3c9-11ea-8151-94f6787dab72.png)

**Comment by ilyve** [comment]
![ball](https://user-images.githubusercontent.com/68177204/87239961-c342d000-c3c9-11ea-9778-4138eb2d10bd.png)

**Comment by illyaveksler** [comment]
![ball0 1](https://user-images.githubusercontent.com/68177204/87239968-d5247300-c3c9-11ea-88d8-dc1140edd4b4.png)
